### ISSUE TITLE
Lombok, Eclipse and JDK10 fails when using the var keyword

### ISSUE THREAD

**Issue by polle** [rzwitserloot/lombok#1676]
If using the 'var' keyword in Eclipse with Lombok and JDK10 I get the following error in Eclipse:

`'var' is not allowed here
`
Using the latest Edge build of Lombok: version: 1.16.21 (2018-04-23 21:43:58 UTC) 

If I remove Lombok it works.

<img width="280" alt="java10-vs-lombok-var" src="https://user-images.githubusercontent.com/371699/39513329-4adb9c98-4df4-11e8-8720-b00643de819e.png">

**Comment by rcsoyer** [comment]
I have the same problem. I'm using the latest release of Eclipse Oxygen. If I put lombok on eclipse, "var" doesn't work. In another issues of lombok project, people said that using lombok edge (https://projectlombok.org/download-edge) would fix. Even with the referred version of lombok, I can't use "var".

**Comment by rspilker** [comment]
Did you remove import `lombok.var`?

**Comment by MikeWrightDev** [comment]
Yep, there is no trace of Lombok in any import.  Here is some sample code:

```
package perfparse;
public class TestLombok {
	public static void main(String[] args) {
		var i = 0;
	}
}
```

In eclipse the "var" has a error on it which says:
'var' is not allowed here	Parse.java	/perfparse/src/main/java/perfparse	line 49	Java Problem

**Comment by gajatko** [comment]
Same in Intellij IDEA. Since a "full JDK 10 supported" had been anounced, I have migrated to JAVA 10 and removed all `import lombok.var` to switch to JAVA's `var` and got IDE errors.
What's even worse, a maven compilation succeds after removing imports, but it fails when imports are present. So I have to migrate back to JDK 8 (because BOTH IDE and maven compilation must work)

**Comment by hc-codersatlas** [comment]
The new 1.6.22 release seems to have fixed this. At least it did for me on Eclipse.

**Comment by gajatko** [comment]
I'll give it a shot. Is an **IntelliJ** user here other than me, who can confirm the issue?

**Comment by MikeWrightDev** [comment]
Still not working on Eclipse Oxygen.3a for me.  Same problem as before.

**Comment by eerokosk** [comment]
Same problem in Visual Studio Code with Lombok version 1.16.22.

If you are using "import lombok.var" VSCode thinks that code is fine but Gradle doesn't build it. If you aren't using import VSCode thinks that code has errors, but Gradle build it without problems.

**Comment by gajatko** [comment]
Looks like a plugin(s) problem to me.

**Comment by MikeWrightDev** [comment]
Is this [commit](https://github.com/rzwitserloot/lombok/commit/2c9c2fefdb346b6dd13a4525395d5a7fb004b299) related to fixing this issue?

**Comment by gajatko** [comment]
Is there any progress on resolving the issue?

**Comment by rspilker** [comment]
Not progress yet, we do not know why if the import is not present the IDEs give errors.

**Comment by rspilker** [comment]
Did someone test this in an IDE without lombok installed?

**Comment by rspilker** [comment]
According to https://www.kevinhooke.com/2018/03/25/taking-a-look-at-java-10-with-eclipse-oxygen-3-with-not-much-success/ this does not work at all.

**Comment by rspilker** [comment]
Hmm, on the other hand https://www.kevinhooke.com/2018/03/26/update-java-10-with-eclipse-oxygen-3a-4-7-3a-rc2-working/ seems to get it working.

**Comment by rspilker** [comment]
We fixed it for Eclipse. for IntelliJ or VSCode, please register issues in their projects.

**Comment by MikeWrightDev** [comment]
Roel, it looks like your patch reacts to the presence of the import lombok.var.  Pretty cool.  I was expecting some patch that just detected JDK 10+ and just disabled the feature.  This is cool because (I think) it says "if the import is there, apply Lombok".

**Comment by aev-mambro2** [comment]
This still happens. Using Lombok 1.18.2 as a java agent for the latest Eclipse Photon with JDK 10.0.2.

**Comment by akrestan** [comment]
Hello, may I ask about how this issue whether it has been resolved if it's been resolved?

With the latest Eclipse Java EE IDE for Web Developers Version: 2018-09 and the latest lombok 1.18.2 I am still getting this error when the Eclipse's JVM is instrumented with -javaagent:lombok.jar even if there is no import of the lombok.var type anywhere in the Java source code and lombok.jar is not among the project's dependencies

**Comment by eerokosk** [comment]
With current version of Lombok (1.18.2) and VS Code everything work like charm when you are using Java 8, Java 9, Java 10 or Java 11. Haven't tested with Java 12 EA yet ;)

VS Code and Eclipse are using similar technologies for Java so i am quite sure that everything works with latest Eclipse as well especially if configured right.

With VS Code i am using following configuration:

{
        "folders": [
                {
                        "path": "."
                }
        ],
        "settings": {
                "java.home": "/opt/java/java-11",
                "java.configuration.updateBuildConfiguration": "automatic"
                "java.jdt.ls.vmargs": "-javaagent:/home/eero/java/lombok/1.18.2/lombok.jar -Xbootclasspath/a:/home/eero/java/lombok/1.18.2/lombok.jar" 
        }
}

Best,

Eero.

**Comment by akrestan** [comment]
....
> "java.jdt.ls.vmargs": "-javaagent:/home/eero/java/lombok/1.18.2/lombok.jar -Xbootclasspath/a:/home/eero/java/lombok/1.18.2/lombok.jar"

Thanks for coming back to me on this, However, with `C:\Eclipse4.9\eclipse.exe -vm c:\JDK11\bin\javaw.exe -vmargs -javaagent:lombok.jar`

with lombok.jar being @ 1.18.2, latest Eclipse for Java EE developers and JDK11 being OpenJDK there is still:

`'var' is not allowed here`

If the instrumentation of the JVM with _lombok.jar_ is removed everything works fine.

**Comment by akrestan** [comment]
With the very latest patch of Eclipse Java EE IDE for Web Developers, Version: 2018-09 (4.9.0) it has begun to work.
