### ISSUE TITLE
[BUG] InvalidArgumentException thrown when using Lombok 1.18.14

### ISSUE THREAD

**Issue by robserm** [rzwitserloot/lombok#2607]
Hi there!
We are using standalone Eclipse JDT parser to parse and then analyze some customer code.
Recently we have added support for code containing Lombok annotations. 
Everything was working fine until 1.18.12, but for 1.18.14 we observe some invalid behavior.
When ASTConverter is converting 'try statement' for a class containing @SneakyThrows annotation an IllegalArgumentException is raised. See the log below. 

It looks like 'catchClauseSourceStart' is evaluated to '-1' by 'retrieveStartingCatchPosition' method
which leads to IllegalArgumentException in 'setSourceRange' method.

int catchClauseSourceStart = retrieveStartingCatchPosition(start, catchArguments[i].sourceStart);
catchClause.setSourceRange(catchClauseSourceStart, catchBlocks[i].sourceEnd - catchClauseSourceStart + 1);

I cannot verify that the same problem occurs for Eclipse IDE because of the 2599 issue.

Another difference between 1.18.12 and 1.18.14 is that artificial AST nodes (from org.eclipse.jdt.internal.compiler.ast package) now do not have '$generatedBy' field. This is valid for at least some nodes created by @SneakyThrows transformation.  So, I would like to ask you is this an expected behaviour or it is a consequence of some missing or incorrectly working functionality?

The stack trace:
java.lang.IllegalArgumentException at parser.util.JdtErrLogHandler.errLog(JdtErrLogHandler.java:17)
[ERROR] [13:37:24,467] Throwable caught at parser.java.JavaParser.parseAll(JavaParser.java:129)
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java:2952)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2972)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2796)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:651)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:205)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3056)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1396)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1064)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:662)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1007)

and the source code:

package lombok.feature12.sneaky.throwss;

import lombok.AllArgsConstructor;
import lombok.NonNull;
import lombok.SneakyThrows;
import java.io.UnsupportedEncodingException;

import lombok.feature09.data.DataExample;

@AllArgsConstructor
public class SneakyThrowsExample implements Runnable {
	
	String name;
       @SneakyThrows(UnsupportedEncodingException.class)
        public String utf8ToString(byte[] bytes) {
           return new String(bytes, "UTF-8");
        }

       @SneakyThrows
       public void run() {
          throw new Throwable();
        }
}

**Comment by rspilker** [comment]
This might be related to #2599

**Comment by rspilker** [comment]
We've just released 1.18.16, please check if that solves this problem as well.

**Comment by Rawi01** [comment]
This one is still there, I can reproduce it using `ant test.eclipse-202006. If I enable `patchCatchReparse` by removing the new witness part the tests pass. Seems like that patch is always required.

**Comment by glatzg** [comment]
The latest lombok.jar, 1.18.16, available for download is actually a 1.18.14. Currently the latest version that works correctly in Eclipse is 1.18.12.

**Comment by robserm** [comment]
> We've just released 1.18.16, please check if that solves this problem as well.

hi rspilker it seems that the jar available at https://projectlombok.org/downloads/lombok.jar is **not** 1.18.16
in the META-INF/MANIFEST.MF has still **Lombok-Version: 1.18.14**

**Comment by glatzg** [comment]
@robserm Thanks for confirming my finding.

**Comment by rspilker** [comment]
The website has been fixed, now the proper version is served. Please retest.

**Comment by rspilker** [comment]
Oh, I see the @Rawi01 suggests we did NOT fix this problem.

**Comment by robserm** [comment]
> Oh, I see the @Rawi01 suggests we did NOT fix this problem.

Yes, that's right, I've just confirmed that the problem is still valid on 1.18.16

**Comment by pbi-qfs** [comment]
I can also still see this problem running `ant test.eclipse-202006`. Any other workaround than calling `addScript` instead of `addScriptIfWitness` in  `patchCatchReparse`?

**Comment by Rawi01** [comment]
Fixed in 67d66be9eccf050a5f3758273ea2d685217f6d5a
