### ISSUE TITLE
[BUG] [Regression] NetBeans integration broken in 1.18.16

### ISSUE THREAD

**Issue by lprimak** [rzwitserloot/lombok#2612]
**Describe the bug**
NetBeans "default" integration fails to process Lombok annotations,
resulting in IDE errors in Lombok projects

**To Reproduce**
Load a Lombok project into NetBeans IDE and see that it has errors

**Expected behavior**
Project is error-free

**Version info (please complete the following information):**
Lombok 1.18.16 and 1.18.14
MacOS, Java 8 (latest)
NetBeans 12 with the latest updates

**Additional context**
Just upgraded to .16 from .12 and seeing this error

**Comment by rspilker** [comment]
I understand you have errors in your code. But I'm not sure if you mean that Lombok silently didn't work, and therefore you have compiler errors since the getters were not generated, or if you suddenly get errors from Lombok code.

Do you have exceptions that occurred?

**Comment by lprimak** [comment]
It looks like NetBeans either fails or not invoking Lombok starting in .14 version.
Because of that, the project is full of errors because none of the Lombok features are invoked anymore.
The code is error-free when compiled in Maven. The errors only show in NetBeans because it no longer works properly
when upgrading to .14

**Comment by lprimak** [comment]
![Screen Shot 2020-10-15 at 8 06 27 PM](https://user-images.githubusercontent.com/1002484/96201355-f72a1600-0f21-11eb-839e-848b7b8e3d93.png)

In the screenshot above, you can see the errors,
and NetBeans not finding a `@Builder`-generated code from Lombok,
when everything worked correctly in the .12 version

**Comment by lprimak** [comment]
Is the above clear? I feel like @rspilker you didn't understand the problem
thanks for checking!

**Comment by lprimak** [comment]
![Screen Shot 2020-10-15 at 8 19 46 PM](https://user-images.githubusercontent.com/1002484/96202048-c814a400-0f23-11eb-91df-48227a8ac162.png)

Screenshot above is from the .12 version of Lombok with the same project and the same setup.
Once again, maven compiles the project just fine under both .12 and .14 versions barring changes related to https://github.com/rzwitserloot/lombok/issues/2610

**Comment by asbachb** [comment]
I guess I'm running into a similar issue but with `@Setter` annotation. The internal NetBeans (12.1) compiler crashes with the new version:

```
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at com.sun.tools.javac.util.Assert.check(Assert.java:46)
	at com.sun.tools.javac.util.Bits.incl(Bits.java:200)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.initParam(Flow.java:2183)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitMethodDef(Flow.java:2110)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:889)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:456)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1679)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.visitClassDef(Flow.java:2052)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:790)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:456)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.scan(Flow.java:1679)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2815)
	at com.sun.tools.javac.comp.Flow$AssignAnalyzer.analyzeTree(Flow.java:2797)
	at com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:219)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1499)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1473)
	at com.sun.tools.javac.api.JavacTaskImpl$1.process(JavacTaskImpl.java:504)
	at com.sun.tools.javac.api.JavacTaskImpl$Filter.run(JavacTaskImpl.java:651)
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:507)
[catch] at org.netbeans.modules.java.source.nbjavac.indexing.MultiPassCompileWorker.compile(MultiPassCompileWorker.java:261)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:361)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:275)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2750)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.access$800(RepositoryUpdater.java:2154)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2636)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$3.call(RepositoryUpdater.java:3300)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$3.call(RepositoryUpdater.java:3255)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$4.run(RepositoryUpdater.java:2127)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2123)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2104)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1500(RepositoryUpdater.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.scanFiles(RepositoryUpdater.java:3255)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$FileListWork.getDone(RepositoryUpdater.java:3785)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3420)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6183)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5834)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6099)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6095)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6091)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6091)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by sephiroth-j** [comment]
same here with NetBeans 12.1 and Lombok 1.18.16 ... same project, simply getter/setter/data annotations, the only change was to update Lombok from 1.18.12 to 1.18.16.

**Comment by lprimak** [comment]
Confirmed. Same issue with 1.18.16

**Comment by Rawi01** [comment]
I just tried this using the latest netbeans and lombok version and a super simple example and it works as expected.
![img](https://user-images.githubusercontent.com/5850477/96514686-45158580-1264-11eb-97bf-3aeb5a466478.png)
Can you share a broken code snippet/project?

**Comment by asbachb** [comment]
@Rawi01 I guess you need to ensure that you installed and activated "The nb-javac java editing support library" and compile on save is enabled for your project.

**Comment by Rawi01** [comment]
@asbachb That was the information I was missing, thanks. It should be possible to debug it now.

**Comment by lprimak** [comment]
Also, if you need a project, you can use this: https://github.com/flowlogix/flowlogix
and change lombok version in https://github.com/flowlogix/flowlogix/blob/master/flowlogix-bom/pom.xml

**Comment by Rawi01** [comment]
@asbachb Your problem should be fixed by the above PR
@lprimak @sephiroth-j  I do not know if your problem is the same or not as you have not shared an error message/stacktrace. Can you try if my fix also solves your issue?

**Comment by asbachb** [comment]
@Rawi01 Do you have a precompiled version you can share? I can verify it within some other bigger non public projects.

**Comment by Rawi01** [comment]
@asbachb Sure [lombok.zip](https://github.com/rzwitserloot/lombok/files/5418448/lombok.zip)

**Comment by sephiroth-j** [comment]
Thanks, I will try it out tomorrow.

**Comment by sephiroth-j** [comment]
@Rawi01 it is better than before. The class is usable now and can be compiled. But it still has that red exclamation mark saying "Error parsing file". The error mark is shown even when only `@RequiredArgsConstructor` is used.

```
@RequiredArgsConstructor
class Foo {
	private final String bar;
}
```

Tested using Java 11.0.8 for Netbeans and the project.

**Comment by sephiroth-j** [comment]
It looks like Netbeans uses two constructors of `om.sun.tools.javac.code.Symbol.VarSymbol`.


The one with 4 arguments as seen here https://github.com/rzwitserloot/lombok/blob/eb78f5c7665833c8e7dedce75fbe102774e370ae/src/stubs/com/sun/tools/javac/code/Symbol.java#L65

But also one with just 3 arguments [here](
https://github.com/apache/netbeans/blob/ee208250c47cc95a60054550ebdcf31f5be533eb/java/java.source.base/src/org/netbeans/api/java/source/ElementUtilities.java#L258) and [here](https://github.com/apache/netbeans/blob/ee208250c47cc95a60054550ebdcf31f5be533eb/java/java.source.base/src/org/netbeans/api/java/source/ElementUtilities.java#L270). The one at line 258 would be the one which would be used for setter and constructors as those methods are of `VOID`-type I guess.

Could this be the cause for the remaining parsing error?

**Comment by Rawi01** [comment]
@sephiroth-j Thanks for testing it, this problem only occurs if the field is static, thats why I missed it. I fixed it and compiled a new version [lombok.zip](https://github.com/rzwitserloot/lombok/files/5430826/lombok.zip)

**Comment by asbachb** [comment]
@Rawi01 For me mostly error are gone with this release. Only for `@Data` annotations. produces errors:

```
import lombok.Data;

@Data
public class Clazz {

  private final String a;

  private final String b;

  private final String c;

  private final String d;
}
```

**Comment by lprimak** [comment]
I am getting issues with `@Builder`, `@SuperBuilder` and `@Data`
as well with the above lombok.zip:

```
java.lang.AssertionError
	at com.sun.tools.javac.code.Type.asMethodType(Type.java:665)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:366)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1171)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:882)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:284)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitClassDef(TypeAnnotations.java:1122)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:788)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:284)
	at com.sun.tools.javac.code.TypeAnnotations.lambda$organizeTypeAnnotationsSignatures$0(TypeAnnotations.java:123)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:197)
	at com.sun.tools.javac.comp.Annotate.unblockAnnotations(Annotate.java:144)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:157)
	at com.sun.tools.javac.main.JavaCompiler.enterDone(JavaCompiler.java:1862)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1149)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1277)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:1183)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1390)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1353)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1243)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.enterTrees(JavacTaskImpl.java:451)
[catch] at org.netbeans.modules.java.source.nbjavac.indexing.MultiPassCompileWorker.compile(MultiPassCompileWorker.java:204)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:361)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:275)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2750)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.access$800(RepositoryUpdater.java:2154)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2636)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork$4.call(RepositoryUpdater.java:5714)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork$4.call(RepositoryUpdater.java:5622)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$4.run(RepositoryUpdater.java:2127)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2123)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2104)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1500(RepositoryUpdater.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5419)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5038)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5821)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3420)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6183)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5834)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6099)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6095)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6091)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6091)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by Rawi01** [comment]
@asbachb Thanks for testing, fixed that problem too.
@lprimak A stacktrace is always useful but a stacktrace + a code snippet that I can use to reproduce it would be even better.

New test version: [lombok.zip](https://github.com/rzwitserloot/lombok/files/5435244/lombok.zip)

This bug is quite hard to fix because I can not reproduce this in a unit test. The problem is that the latest lombok version now shares method parameter names with other annotation processors. Turining of this feature in NetBeans should solve this issue but might lead to some inconsistency.

**Comment by lprimak** [comment]
@Rawi01 Thanks for taking a look again. I am working with NetBeans 12 and https://github.com/flowlogix/flowlogix/tree/master/jakarta-ee
so you can just clone that and open it and it's four sub-projects in NetBeans and see if they have any issues

**Comment by lprimak** [comment]
Just tested again with the new test version, unfortunately exception still occurs.

Looks like `@Data` and `@Builder / @SuperBuilder` cause issues
Specifically the projects not compiling are https://github.com/flowlogix/flowlogix/tree/master/jakarta-ee/flowlogix-jee and https://github.com/flowlogix/flowlogix/tree/master/jakarta-ee/flowlogix-datamodel


```
java.lang.AssertionError
	at com.sun.tools.javac.code.Type.asMethodType(Type.java:665)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:366)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1171)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:882)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:284)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitClassDef(TypeAnnotations.java:1122)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:788)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.scan(TypeAnnotations.java:284)
	at com.sun.tools.javac.code.TypeAnnotations.lambda$organizeTypeAnnotationsSignatures$0(TypeAnnotations.java:123)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:197)
	at com.sun.tools.javac.comp.Annotate.unblockAnnotations(Annotate.java:144)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:157)
	at com.sun.tools.javac.main.JavaCompiler.enterDone(JavaCompiler.java:1862)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1149)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1277)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:1183)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1390)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1353)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1243)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.enterTrees(JavacTaskImpl.java:451)
[catch] at org.netbeans.modules.java.source.nbjavac.indexing.MultiPassCompileWorker.compile(MultiPassCompileWorker.java:204)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:361)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:275)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2750)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.access$800(RepositoryUpdater.java:2154)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2636)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:540)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2634)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork$4.call(RepositoryUpdater.java:5714)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork$4.call(RepositoryUpdater.java:5622)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$4.run(RepositoryUpdater.java:2127)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2123)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2104)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1500(RepositoryUpdater.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSource(RepositoryUpdater.java:5749)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$AbstractRootsWork.scanSources(RepositoryUpdater.java:5419)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$RootsWork.getDone(RepositoryUpdater.java:5038)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3420)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6183)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5834)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6099)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:83)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6095)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6091)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6091)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by lprimak** [comment]
Just tried NetBeans 12.1 with the same result

**Comment by asbachb** [comment]
AFAIK `@Builder` was already broken previous this bug. I'm unsure if the problems are connected.

**Comment by lprimak** [comment]
> AFAIK `@Builder` was already broken previous this bug. I'm unsure if the problems are connected.

For me, @Builder worked in .12 so this is broken since then and I don't see any other exceptions, so it could be either or

**Comment by jiai** [comment]
Same situation here: 1.18.12 is working fine. When using 1.18.14 and 1.18.16 Netbeans is full of error markers (the Maven project itself is compiling fine).
Windows 10, Netbeans 12.1, AdoptOpenJdk 15.0.1+9 Hotspot.

**Comment by Rawi01** [comment]
@lprimak I can open this project using NetBeans and there are no errors. If there still is something that does not work it would be really useful if you can share minimal code snippets or a small sample project that only contains broken stuff.

**Comment by lprimak** [comment]
That's because it's using Lombok 1.18.12, if you update flowlogix-bom/pom.xml with the latest version and restart NetBeans, the problems will show up.

> @lprimak I can open this project using NetBeans and there are no errors. If there still is something that does not work it would be really useful if you can share minimal code snippets or a small sample project that only contains broken stuff.

**Comment by Rawi01** [comment]
@lprimak Of course I have changed the version and fixed the `@Delegate` issue.

**Comment by lprimak** [comment]
@Rawi01 Is this with the lombok.zip from above? Or is there another, newer one I should try?

**Comment by Rawi01** [comment]
@lprimak This one: https://github.com/rzwitserloot/lombok/issues/2612#issuecomment-716172875

**Comment by lprimak** [comment]
I have re-confirmed the issue still exists.
Here is a simplest case I can come up with that fails
Remember that the error marker is only on the file name, not inside the file itself
![Screen Shot 2020-10-27 at 4 33 12 PM](https://user-images.githubusercontent.com/1002484/97364477-1dc94480-1872-11eb-9756-460dec52b4fd.png)
![Screen Shot 2020-10-27 at 4 33 33 PM](https://user-images.githubusercontent.com/1002484/97364515-2ae63380-1872-11eb-86ce-a947bef657dc.png)


```
@RequiredArgsConstructor
public class Sample {
    private final int one;
    private final int two;
}
```

**Comment by lprimak** [comment]
@Rawi01 well, that was embarrassing, 
I forgot to update the version from https://github.com/rzwitserloot/lombok/issues/2612#issuecomment-715461060 to the latest internally.

I can confirm that the new version in the above comment works correctly!
Thank you!

**Comment by lprimak** [comment]
Fixed in Lombok > 1.18.16

**Comment by lprimak** [comment]
fixed by PR https://github.com/rzwitserloot/lombok/pull/2621

**Comment by sephiroth-j** [comment]
> 
> 
> @Rawi01 well, that was embarrassing,
> I forgot to update the version from [#2612 (comment)](https://github.com/rzwitserloot/lombok/issues/2612#issuecomment-715461060) to the latest internally.
> 
> I can confirm that the new version in the above comment works correctly!
> Thank you!

I can confirm this as well.

**Comment by sysmat** [comment]
Here is the same NB 12.1, The nb-javac java editing support library, lombok 1.18.16  it is still broken

**Comment by didiez** [comment]
> Here is the same NB 12.1, The nb-javac java editing support library, lombok 1.18.16 it is still broken

It seems to be fixed in edge-release (https://projectlombok.org/download-edge)

Netbeans issues related to this: 
- https://issues.apache.org/jira/browse/NETBEANS-5002
- https://issues.apache.org/jira/browse/NETBEANS-5038

Is the any ETA for a stable version with this fix?

**Comment by lprimak** [comment]
Yes, we need stable release

**Comment by rspilker** [comment]
We're currently working towards a new release, meaning we're not integrating risky features or pull requests. We expect a new release within a week.

**Comment by davitp** [comment]
Good Day,
Can anyone explain why this issue happens? I was using Lombok 1.18.16 for some time with Netbeans 11, 12.1, 12.2 and everything was fine. Apparently, it stopped recognizing classes annotated with Lombok with the same error that is discussed here. 

Any plans for a stable release including this?

**Comment by lprimak** [comment]
It's been 3 months since the last release, NetBeans still broken.
It's time for another release.
Thank you @rspilker @rzwitserloot

**Comment by esafzay** [comment]
I still have this issue on Netbeans 12.3 with Lombok 1.18.20
