### ISSUE TITLE
StackOverflowError Occur When Use @Data annotation [but It is working normal setter and gettter]

### ISSUE THREAD

**Issue by winkumar** [rzwitserloot/lombok#993]
Response:
-----------------
{
  "timestamp": 1451645295281,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "java.lang.StackOverflowError",
  "message": null,
  "path": "/api/v1/teams/1/availableMembers"
}

StackTrace:
-------------------
at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at org.hibernate.collection.internal.PersistentSet.endRead(PersistentSet.java:344)
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:251)
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:238)
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:211)
	at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceInitializerImpl.java:168)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:255)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:218)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:140)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:138)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:100)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:92)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1897)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:558)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:260)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:554)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142)
	at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:447)
	at com.test.model.Team.hashCode(Team.java:21)
	at com.test.model.TeamMember.hashCode(TeamMember.java:21)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)

**Comment by winkumar** [comment]
The StackOverflowError and OutOfMemoryError occurs due to circular reference,
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/en/Appendix/Lombok.html

**Comment by winkumar** [comment]
Some place still i got "java.lang.StackOverflowError",

I am using 
@ToString(exclude = {"clients"}) 

org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142)
at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:447)
at com.test.model.Team.hashCode(Team.java:21)
at com.test.model.TeamMember.hashCode(TeamMember.java:21)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)

**Comment by SharpMan** [comment]
for heavy classes use apache lang -> StringUtils

**Comment by abitgen** [comment]
Solved Here -> https://github.com/rzwitserloot/lombok/issues/1007

**Comment by Maaartinus** [comment]
@winkumar You're excluding the field from `toString`, but still get an exception from `hashCode`. What about adding another exclusion?
